language: node_js
dist: trusty
addons:
  firefox: latest
node_js:
- '13'
- '12'
- '10'
matrix:
  allow_failures:
    - node_js: '13'
before_install:
- sudo pip install futoin-cid
script:
- rm -rf node_modules
- nodeVer=$TRAVIS_NODE_VERSION nodeEnv=development cid prepare
- nodeVer=$TRAVIS_NODE_VERSION nodeEnv=development cid run test
